import "ace-css";

import VOutside from "./directives/outside";
import VFocus from "./directives/focus";
import VToggle from "./directives/toggle";

import Accordion from "./components/accordion.vue";
import Alert from "./components/alert.vue";
import Animation from "./components/animation.vue";
import Badge from "./components/badge.vue";
import Ball from "./components/ball.vue";
import BaseErrors from "./components/base_errors.vue";
import Btn from "./components/btn.vue";
import ButtonGroup from "./components/button_group.vue";
import Card from "./components/card.vue";
import CheckGroup from "./components/check_group.vue";
import Checkbox from "./components/checkbox.vue";
import DataForm from "./components/data_form.vue";
import DateV from "./components/date.vue";
import Dropdown from "./components/dropdown.vue";
import FadeTransition from "./components/fade_transition.vue";
import Fieldset from "./components/fieldset.vue";
import Icon from "./components/icon.vue";
import InfoBox from "./components/info_box.vue";
import InputBox from "./components/input-box.vue";
import KeyValue from "./components/key_value.vue";
import ListPage from "./components/list_page.vue";
import List from "./components/list.vue";
import Many from "./components/many.vue";
import Modal from "./components/modal.vue";
import Multi from "./components/multi.vue";
import Outside from "./components/outside.vue";
import Pager from "./components/pager.vue";
import Progress from "./components/progress.vue";
import RadioGroup from "./components/radio-group.vue";
import Radio from "./components/radio.vue";
import ScaleTransition from "./components/scale_transition.vue";
import SideModal from "./components/side_modal.vue";
import SlideTransition from "./components/slide_transition.vue";
import Spinner from "./components/spinner.vue";
import StepHeader from "./components/step_header.vue";
import Step from "./components/step.vue";
import StepperHeader from "./components/stepper_header.vue";
import StepperItem from "./components/stepper_item.vue";
import Stepper from "./components/stepper.vue";
import Submit from "./components/submit.vue";
import TabGroup from "./components/tab_group.vue";
import TabHeader from "./components/tab_header.vue";
import Tab from "./components/tab.vue";
import TagGroup from "./components/tag_group.vue";
import ThumbModal from "./components/thumb_modal.vue";
import Toggle from "./components/toggle.vue";
import UploadButton from "./components/upload_button.vue";

export default (Vue) => {
  Vue.directive("outside", VOutside);
  Vue.directive("focus", VFocus);
  Vue.directive("toggle", VToggle);

  Vue.component("Accordion", Accordion);
  Vue.component("Alert", Alert);
  Vue.component("Animation", Animation);
  Vue.component("Badge", Badge);
  Vue.component("Ball", Ball);
  Vue.component("BaseErrors", BaseErrors);
  Vue.component("Btn", Btn);
  Vue.component("ButtonGroup", ButtonGroup);
  Vue.component("Card", Card);
  Vue.component("CheckGroup", CheckGroup);
  Vue.component("Checkbox", Checkbox);
  Vue.component("DataForm", DataForm);
  Vue.component("DateV", DateV);
  Vue.component("Dropdown", Dropdown);
  Vue.component("FadeTransition", FadeTransition);
  Vue.component("Fieldset", Fieldset);
  Vue.component("Icon", Icon);
  Vue.component("InfoBox", InfoBox);
  Vue.component("InputBox", InputBox);
  Vue.component("KeyValue", KeyValue);
  Vue.component("ListPage", ListPage);
  Vue.component("List", List);
  Vue.component("Many", Many);
  Vue.component("Modal", Modal);
  Vue.component("Multi", Multi);
  Vue.component("Outside", Outside);
  Vue.component("Pager", Pager);
  Vue.component("Progress", Progress);
  Vue.component("RadioGroup", RadioGroup);
  Vue.component("Radio", Radio);
  Vue.component("ScaleTransition", ScaleTransition);
  Vue.component("SideModal", SideModal);
  Vue.component("SlideTransition", SlideTransition);
  Vue.component("Spinner", Spinner);
  Vue.component("StepHeader", StepHeader);
  Vue.component("Step", Step);
  Vue.component("StepperHeader", StepperHeader);
  Vue.component("StepperItem", StepperItem);
  Vue.component("Stepper", Stepper);
  Vue.component("Submit", Submit);
  Vue.component("TabGroup", TabGroup);
  Vue.component("TabHeader", TabHeader);
  Vue.component("Tab", Tab);
  Vue.component("TagGroup", TagGroup);
  Vue.component("ThumbModal", ThumbModal);
  Vue.component("Toggle", Toggle);
  Vue.component("UploadButton", UploadButton);
};
